### ISSUE TITLE
Improve message for broken markup.

### ISSUE THREAD

**Issue by matthid** [fsprojects/FSharp.Formatting#370]
This will be a collection of error messages to improve:
- [ ] https://github.com/tpetricek/FSharp.Formatting/issues/335
- [ ] https://github.com/tpetricek/FSharp.Formatting/issues/360
- [ ] https://github.com/tpetricek/FSharp.Formatting/issues/366
- [ ] 
  
  ```
  ![Some alt text 'Stream'](Content/images/test.jpg test-screen")
  ```
  
  Notice the missing `"`, this currently crashes with a cryptic message:
  
  ```
  System.ArgumentOutOfRangeException: Length cannot be less than zero.
  Parameter name: length
  at System.String.Substring(Int32 startIndex, Int32 length)
  at FSharp.Markdown.Parser.getLinkAndTitle(String _arg1) in c:\Projects\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 27
  at FSharp.Markdown.Parser.parseChars@223-21.Invoke(Unit unitVar) in c:\Projects\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 223
  at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@881.Invoke(Unit unitVar0)
  at Microsoft.FSharp.Collections.SeqModule.Append@1188-1.Invoke(Unit unitVar0)
  at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@432.Invoke(Unit unitVar0)
  at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g)
  at Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator`1.System-Collections-IEnumerator-MoveNext()
  at <StartupCode$FSharp-Core>.$Seq.MoveNextImpl@819.GenerateNext(IEnumerable`1& next)
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
  at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
  at FSharp.Markdown.Parser.parseParagraphs@568.Invoke(Unit unitVar) in c:\Projects\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 635
  at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@881.Invoke(Unit unitVar0)
  at FSharp.Markdown.Parser.formatTree@616-2.GenerateNext(IEnumerable`1& next) in c:\Projects\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 616
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
  at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
  at FSharp.Markdown.Parser.formatTree@615-1.GenerateNext(IEnumerable`1& next) in c:\Projects\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 615
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
  at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
  at FSharp.Markdown.Parser.formatTree@612(ParsingContext ctx, FSharpList`1 nodes) in c:\Projects\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 613
  at FSharp.Markdown.Parser.parseParagraphs@568.Invoke(Unit unitVar) in c:\Projects\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 601
  at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@881.Invoke(Unit unitVar0)
  at Microsoft.FSharp.Collections.SeqModule.Append@1188-1.Invoke(Unit unitVar0)
  at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@432.Invoke(Unit unitVar0)
  at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g)
  at Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator`1.System-Collections-IEnumerator-MoveNext()
  at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
  at FSharp.Markdown.Markdown.Parse(String text, String newline) in c:\Projects\FSharp.Formatting\src\FSharp.Markdown\Main.fs:line 56
  at FSharp.Literate.ParseMarkdown.parseMarkdown(String file, String text) in c:\Projects\FSharp.Formatting\src\FSharp.Literate\ParseMarkdown.fs:line 9
  at FSharp.Literate.Literate.ParseMarkdownFile[b](String path, FSharpOption`1 formatAgent, FSharpOption`1 compilerOptions, FSharpOption`1 definedSymbols, FSharpOption`1 references, FSharpOption`1 fsiEvaluator) in c:\Projects\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 85
  ```

**Comment by neoeinstein** [comment]
It has been a little while since I was tinkering with this, but regarding #360 and the silent discard of exceptions during evaluation, I think that it is currently explicit here:
https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.Literate/Evaluator.fs#L170

I would like it if this were changed so that the evaluation would return the error message as `output` and bind `it`/`result` (depending on how the block was defined) to the exception. I could take a swing at, but won't get to it until the weekend at the least.

**Comment by dsyme** [comment]
Closing this very old issue
