### ISSUE TITLE
`NullReferenceException` when running `dotnet fsdocs build --eval`

### ISSUE THREAD

**Issue by gbaydin** [fsprojects/FSharp.Formatting#596]
I'm running docs generation for [DiffSharp](https://github.com/DiffSharp/DiffSharp) and I get the following output:

```
dotnet fsdocs build --eval
restored project state from '.fsdocs/cache'
  root --> https://diffsharp.github.io/
  fsdocs-authors --> Atılım Güneş Baydin, Barak A. Pearlmutter and DiffSharp contributors
  fsdocs-collection-name --> DiffSharp
  fsdocs-collection-name-link --> https://diffsharp.github.io/
  fsdocs-copyright --> Copyright 2014-2020
  fsdocs-logo-src --> https://diffsharp.github.io/img/logo.png
  fsdocs-navbar-position --> fixed-right
  fsdocs-theme --> default
  fsdocs-logo-link --> https://diffsharp.github.io/
  fsdocs-license-link --> https://github.com/DiffSharp/DiffSharp/blob/master/LICENSE.md
  fsdocs-release-notes-link --> https://github.com/DiffSharp/DiffSharp/blob/master/RELEASE_NOTES.md
  fsdocs-package-project-url --> https://diffsharp.github.io/
  fsdocs-package-license-expression --> BSD-2-Clause
  fsdocs-package-icon-url --> {{fsdocs-package-icon-url}}
  fsdocs-package-tags --> F# fsharp ML AI Machine Learning PyTorch Automatic Differentiation Gradients
  fsdocs-package-version --> 1.0.0-local-200909
  fsdocs-repository-link --> https://github.com/DiffSharp/DiffSharp/
  fsdocs-repository-branch --> dev
  fsdocs-repository-commit --> {{fsdocs-repository-commit}}
using extra content from /home/gunes/.nuget/packages/fsharp.formatting.commandtool/7.2.6/extras
Error : 
System.NullReferenceException: Object reference not set to an instance of an object.
   at <StartupCode$fsdocs>.$BuildCommand.clo@450-3.GenerateNext(IEnumerable`1& next) in E:\GitHub\dsyme\fsharp-core-docs\FSharp.Formatting\src\FSharp.Formatting.CommandTool\BuildCommand.fs:line 555
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$fsdocs>.$BuildCommand.clo@561-20.GenerateNext(IEnumerable`1& next) in E:\GitHub\dsyme\fsharp-core-docs\FSharp.Formatting\src\FSharp.Formatting.CommandTool\BuildCommand.fs:line 577
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$fsdocs>.$BuildCommand.Convert@594.GenerateNext(IEnumerable`1& next) in E:\GitHub\dsyme\fsharp-core-docs\FSharp.Formatting\src\FSharp.Formatting.CommandTool\BuildCommand.fs:line 594
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$fsdocs>.$BuildCommand.runDocContentPhase1@868-1.Invoke(Unit unitVar0) in E:\GitHub\dsyme\fsharp-core-docs\FSharp.Formatting\src\FSharp.Formatting.CommandTool\BuildCommand.fs:line 878
   at <StartupCode$fsdocs>.$BuildCommand.protect@703(FSharpFunc`2 f) in E:\GitHub\dsyme\fsharp-core-docs\FSharp.Formatting\src\FSharp.Formatting.CommandTool\BuildCommand.fs:line 705
generating model for API docs...
Generating output/reference/index.html
Generating output/reference/diffsharp.html
Generating output/reference/diffsharp-backends.html
Generating output/reference/diffsharp-data.html
Generating output/reference/diffsharp-distributions.html
Generating output/reference/diffsharp-model.html
Generating output/reference/diffsharp-optim.html
Generating output/reference/diffsharp-backendmodule.html
Generating output/reference/diffsharp-devicemodule.html
Generating output/reference/diffsharp-dtypemodule.html
Generating output/reference/diffsharp-dtypeglobalops.html
Generating output/reference/diffsharp-util.html
Generating output/reference/diffsharp-util-array.html
Generating output/reference/diffsharp-util-shapemodule.html
Generating output/reference/diffsharp-util-globalnestinglevel.html
Generating output/reference/diffsharp-util-nestinglevel.html
Generating output/reference/diffsharp-util-random.html
Generating output/reference/diffsharp-util-shape.html
Generating output/reference/diffsharp-backend.html
Generating output/reference/diffsharp-device.html
Generating output/reference/diffsharp-devicetype.html
Generating output/reference/diffsharp-dtype.html
Generating output/reference/diffsharp-tensor.html
Generating output/reference/diffsharp-tensorop.html
Generating output/reference/diffsharp-dsharp.html
Generating output/reference/diffsharp-scalar.html
Generating output/reference/diffsharp-backends-backendstatics.html
Generating output/reference/diffsharp-backends-rawtensor.html
Generating output/reference/diffsharp-data-dataloader.html
Generating output/reference/diffsharp-data-dataset.html
Generating output/reference/diffsharp-data-mnist.html
Generating output/reference/diffsharp-data-tensordataset.html
Generating output/reference/diffsharp-distributions-bernoulli.html
Generating output/reference/diffsharp-distributions-categorical.html
Generating output/reference/diffsharp-distributions-distribution-1.html
Generating output/reference/diffsharp-distributions-empirical-1.html
Generating output/reference/diffsharp-distributions-normal.html
Generating output/reference/diffsharp-distributions-tensordistribution.html
Generating output/reference/diffsharp-distributions-uniform.html
Generating output/reference/diffsharp-model-batchnorm1d.html
Generating output/reference/diffsharp-model-batchnorm2d.html
Generating output/reference/diffsharp-model-batchnorm3d.html
Generating output/reference/diffsharp-model-conv1d.html
Generating output/reference/diffsharp-model-conv2d.html
Generating output/reference/diffsharp-model-conv3d.html
Generating output/reference/diffsharp-model-dropout.html
Generating output/reference/diffsharp-model-dropout2d.html
Generating output/reference/diffsharp-model-dropout3d.html
Generating output/reference/diffsharp-model-linear.html
Generating output/reference/diffsharp-model-mode.html
Generating output/reference/diffsharp-model-model.html
Generating output/reference/diffsharp-model-parameter.html
Generating output/reference/diffsharp-model-parameterdict.html
Generating output/reference/diffsharp-model-weight.html
Generating output/reference/diffsharp-optim-adam.html
Generating output/reference/diffsharp-optim-optimizer.html
Generating output/reference/diffsharp-optim-sgd.html
Generating output/reference/diffsharp-optim-optim.html
```

The documentation seems to be generated but there is a `NullReferenceException` following `using extra content from /home/gunes/.nuget/packages/fsharp.formatting.commandtool/7.2.6/extras`. 

Additionally, it is also interesting that the error message is leaking some private information (directory names in @dsyme 's computer). I don't know if this is the expected behavior in the error message.

**Comment by dsyme** [comment]
thanks, will look into it

Can be worth nuking `.fsdocs/cache` though this is normally done automatically, I don't think that's the problem here

**Comment by dsyme** [comment]
Re private names - it's not a big problem, we'll move to building the packages on the CI server

**Comment by dsyme** [comment]
I'll close this as docs generation is working in DiffSharp with latest verson
