### ISSUE TITLE
Generating API documentation for a library that uses 3rd-party dependencies fails

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsprojects/FSharp.Formatting#616]
Consider [the attached example library](https://github.com/fsprojects/FSharp.Formatting/files/5388146/FsDocsBug.zip). It defines a library with a class with a property that returns a `Newtonsoft.Linq.JToken`.

`dotnet fsdocs build`ing the project fails with

```
Could not read comments from entity 'FsDocsBug.Inner.MyType': System.InvalidOperationException: The entity or value 'Newtonsoft.Json.Linq.JToken' does not exist or is in an unresolved assembly. You may need to add a reference to ass
embly 'Newtonsoft.Json'
   at FSharp.Compiler.SourceCodeServices.Impl.dflt@113[a](String tupledArg0, String tupledArg1) in /Users/chethusk/oss/FCS/src/fsharp/symbols/Symbols.fs:line 75
   at FSharp.Compiler.SourceCodeServices.Impl.protect[a](FSharpFunc`2 f)
   at FSharp.Compiler.SourceCodeServices.FSharpEntity.get_MembersFunctionsAndValues() in /Users/chethusk/oss/FCS/src/fsharp/symbols/Symbols.fs:line 597
   at FSharp.Formatting.ApiDocs.SymbolReader.getMembers@1886-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at FSharp.Formatting.ApiDocs.SymbolReader.readType@1882.Invoke(String cat, Int32 catidx, Boolean exclude, IDictionary`2 _cmds, ApiDocComment comment) in C:\GitHub\dsyme\FSharp.Formatting\src\FSharp.Formatting.ApiDocs\GenerateMode
l.fs:line 1899
   at FSharp.Formatting.ApiDocs.SymbolReader.readCommentsInto$cont@1743[c](FSharpSymbol sym, FSharpFunc`2 f, FSharpOption`1 nsdocs, ApiDocComment comment, IDictionary`2 cmds, String cat, Unit unitVar) in C:\GitHub\dsyme\FSharp.Forma
tting\src\FSharp.Formatting.ApiDocs\GenerateModel.fs:line 1753
```

__How to generate documentation for a library that uses 3rd-party types in its API?__

It looks like that the command tool has trouble finding the references for the assemblies it processes. One solution would have been through the [`AssemblyDependencyResolver`](https://docs.microsoft.com/en-gb/dotnet/api/system.runtime.loader.assemblydependencyresolver) class.

**Comment by dsyme** [comment]
Hmm interesting, yes.  I guess ideally we'd point everything at a tests folder (i.e. an application) that has all dependencies bundled.

**Comment by TheAngryByrd** [comment]
I did this recently in MiniScaffold where we do a [`dotnet publish`](https://github.com/TheAngryByrd/MiniScaffold/pull/219/files#diff-35aa06a870b9dac853c9baaf220affbfddfcde3213220227906cb02b977f6d02R200) on the projects and use the publish output directory for the [Content docs](https://github.com/TheAngryByrd/MiniScaffold/pull/219/files#diff-35aa06a870b9dac853c9baaf220affbfddfcde3213220227906cb02b977f6d02R126) and the [references docs](https://github.com/TheAngryByrd/MiniScaffold/pull/219/files#diff-35aa06a870b9dac853c9baaf220affbfddfcde3213220227906cb02b977f6d02R217).

---

Aside: I didnt realize how far along you've gotten with fsdocs.  I think it's time to for me to consider retiring my docsTool stuff and contribute to this repo.

**Comment by teo-tsirpanis** [comment]
We can't do that from the command tool though. 😢

**Comment by TheAngryByrd** [comment]
> @TheAngryByrd we can't do that from the command tool though. 😢

Yeah I was more pointing to how this I solved the problem and how this repo could fix it.

**Comment by kMutagene** [comment]
Same situation, different stack trace (from [Dash.NET](https://github.com/plotly/Dash.NET)):

```
API docs:
  generating model for 1 assemblies in API docs...
  loading 1 assemblies...
  registering entities for assembly Dash.NET...
Error :
FSharp.Compiler.ErrorLogger+UnresolvedPathReferenceNoRange: Assembly: Giraffe, full path: Giraffe.GiraffeViewEngine.XmlNode
   at FSharp.Compiler.TypedTree.CcuThunk.EnsureDerefable(String[] requiringPath) in F:\workspace\_work\1\s\src\fsharp\TypedTree.fs:line 5103
   at FSharp.Compiler.TypedTree.NonLocalEntityRef.TryDeref(Boolean canError) in F:\workspace\_work\1\s\src\fsharp\TypedTree.fs:line 3157
   at FSharp.Compiler.TypedTree.EntityRef.get_Deref() in F:\workspace\_work\1\s\src\fsharp\TypedTree.fs:line 3254
   at FSharp.Compiler.TypedTreeOps.stripTyEqnsA(TcGlobals g, Boolean canShortcut, TType ty) in F:\workspace\_work\1\s\src\fsharp\TypedTreeOps.fs:line 739
   at FSharp.Compiler.TypedTreeOps.isUnitTy(TcGlobals g, TType ty) in F:\workspace\_work\1\s\src\fsharp\TypedTreeOps.fs:line 1666
   at FSharp.Compiler.TypedTreeOps.GetTopValTypeInCompiledForm(TcGlobals g, ValReprInfo topValInfo, Int32 numEnclosingTypars, TType ty, range m) in F:\workspace\_work\1\s\src\fsharp\TypedTreeOps.fs:line 2324
   at FSharp.Compiler.TypedTreeOps.XmlDocSigOfVal(TcGlobals g, Boolean full, String path, Val v) in F:\workspace\_work\1\s\src\fsharp\TypedTreeOps.fs:line 8080
   at FSharp.Compiler.SourceCodeServices.SymbolHelpers.GetXmlDocSigOfScopedValRef(TcGlobals g, EntityRef tcref, ValRef vref) in F:\workspace\_work\1\s\src\fsharp\symbols\SymbolHelpers.fs:line 541
   at FSharp.Compiler.SourceCodeServices.FSharpMemberOrFunctionOrValue.get_XmlDocSig() in F:\workspace\_work\1\s\src\fsharp\symbols\Symbols.fs:line 1845
   at FSharp.Formatting.ApiDocs.CrossReferences.getXmlDocSigForMember(FSharpMemberOrFunctionOrValue memb) in C:\Users\Kevin\source\repos\fsprojects\FSharp.Formatting\src\FSharp.Formatting.ApiDocs\GenerateModel.fs:line 575
   at FSharp.Formatting.ApiDocs.CrossReferenceResolver.registerMember(FSharpMemberOrFunctionOrValue memb) in C:\Users\Kevin\source\repos\fsprojects\FSharp.Formatting\src\FSharp.Formatting.ApiDocs\GenerateModel.fs:line 647
   at FSharp.Formatting.ApiDocs.CrossReferenceResolver.registerEntity(FSharpEntity entity) in C:\Users\Kevin\source\repos\fsprojects\FSharp.Formatting\src\FSharp.Formatting.ApiDocs\GenerateModel.fs:line 669
   at <StartupCode$FSharp-Formatting-ApiDocs>.$GenerateModel.assemblies@2149.Invoke(FSharpEntity arg00) in C:\Users\Kevin\source\repos\fsprojects\FSharp.Formatting\src\FSharp.Formatting.ApiDocs\GenerateModel.fs:line 2149
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 497
   at FSharp.Formatting.ApiDocs.ApiDocModel.Generate(FSharpList`1 projects, String collectionName, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, Boolean qualify, FSharpOption`1 urlRangeHighlight, String root, FSharpList`1 substitutions, Boolean strict) in C:\Users\Kevin\source\repos\fsprojects\FSharp.Formatting\src\FSharp.Formatting.ApiDocs\GenerateModel.fs:line 2149
   at FSharp.Formatting.ApiDocs.ApiDocs.GenerateHtmlPhased[a](FSharpList`1 inputs, String output, String collectionName, FSharpList`1 substitutions, FSharpOption`1 template, FSharpOption`1 root, FSharpOption`1 qualify, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, FSharpOption`1 urlRangeHighlight, FSharpOption`1 strict) in C:\Users\Kevin\source\repos\fsprojects\FSharp.Formatting\src\FSharp.Formatting.ApiDocs\ApiDocs.fs:line 54
   at <StartupCode$fsdocs>.$BuildCommand.runGeneratePhase1@577-1.Invoke(Unit unitVar0) in C:\Users\Kevin\source\repos\fsprojects\FSharp.Formatting\src\FSharp.Formatting.CommandTool\BuildCommand.fs:line 601
   at <StartupCode$fsdocs>.$BuildCommand.protect@338(CoreBuildOptions this, FSharpFunc`2 f) in C:\Users\Kevin\source\repos\fsprojects\FSharp.Formatting\src\FSharp.Formatting.CommandTool\BuildCommand.fs:line 340
```
Would it be valuable to add a command line argument (maybe something like `--dependencyResolvePaths` or `--dependencyPath(s)`) to pass folders such as the `packages` folder when using paket with `storage:packages` or the nuget cache path (which may be a custom path) or is there already something similar going on?

**Comment by dsyme** [comment]
> Would it be valuable to add a command line argument (maybe something like --dependencyResolvePaths or --dependencyPath(s)) to pass folders such as the packages folder when using paket with storage:packages or the nuget cache path (which may be a custom path) or is there already something similar going on?

We could, perhaps as an interim measure, though I think this is the solution we may need to follow:  "ideally we'd point everything at a tests folder (i.e. an application) that has all dependencies bundled."

It may also be possible to set some flag in the project file marking the project as a test DLL (even if it actually isn't), to ensure dependencies get copied to the output directory.  That may have the side effect of zero tests being found on test execution though.  Not sure if it's a problem

**Comment by teo-tsirpanis** [comment]
.NET Core has [a type that does the entire work for us](https://docs.microsoft.com/en-gb/dotnet/api/system.runtime.loader.assemblydependencyresolver).

**Comment by dsyme** [comment]
> .NET Core has a type that does the entire work for us.

I see thanks, nice. Maybe that's enough.

**Comment by KevinRansom** [comment]
@teo-tsirpanis , I will take a look I think I need it for a similar notebook scenario anyway.

**Comment by KevinRansom** [comment]
@dsyme , @teo-tsirpanis , I think the suggested API, may help us out in FSI.  However, I don't think the compiler itself should work off ambient types, the compiler ideally knows all of the assemblies that contribute to a successful build.  If this scenario is important for fsdocs then I suppose that fsdocs should implement an AssemblyLoadContext that does this work.

**Comment by nojaf** [comment]
Hello, we are having the same problem. One project has a NuGet dependency so the cracking fails from the command line.
A workaround is to provide the reference we are missing:
 > --fscoptions " " -r:C:\Users\nojaf\Projects\fantomas\src\Fantomas\bin\Debug\net6.0\SemanticVersioning.dll"

Notice that this requires an additional space before the `-r`, see https://github.com/commandlineparser/commandline/issues/58.

Would a PR be accepted that trims all entries of `otherflags` in 
https://github.com/fsprojects/FSharp.Formatting/blob/9cb0c7daf97b1b551f5fd4e0779eee6d6a1ff99a/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L2988
?

This would resolve our generation problem when running the tool.

//cc @yisusalanpng

**Comment by dsyme** [comment]
Yes, sounds good

**Comment by joemphilips** [comment]
FYI, I encountered a same error when I use the newest SDK version `6.0.400`
But it worked fine when I downgraded to `6.0.303`.
I couldn't identify what exactly is the problem by reading [the release notes](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.8/6.0.8.md?WT.mc_id=dotnet-35129-website) but the downgrade was good enough for me.
