### ISSUE TITLE
No mention of <GenerateDocumentationFile> in docs

### ISSUE THREAD

**Issue by davedawkins** [fsprojects/FSharp.Formatting#690]
New user experience. I run the command as directed, but get these errors (see end). One message is
```
  skipping project 'App.fsproj' because it doesn't have <GenerateDocumentationFile>
```
OK, how do I add that? Searching docs for `GenerateDocumentationFile` shows no mention, so I'm unable to fix this myself (quickly).

Searching wider, I found that I can add the following
```
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
```
I hope to create a PR for the docs with this information.

Full error log
```
david@davebook Sutil % dotnet tool install FSharp.Formatting.CommandTool
You can invoke the tool from this directory using the following commands: 'dotnet tool run fsdocs' or 'dotnet fsdocs'.
Tool 'fsharp.formatting.commandtool' (version '11.4.1') was successfully installed. Entry is added to the manifest file /Users/david/projects/Sutil/.config/dotnet-tools.json.
david@davebook Sutil % dotnet fsdocs build
getting projects from solution file /Users/david/projects/Sutil/Sutil.sln
  skipping project 'Tests.fsproj' because it looks like a test project
cracking projects...
  skipping project 'App.fsproj' because it doesn't have <GenerateDocumentationFile>
  skipping project 'DevTools.fsproj' because it doesn't have <GenerateDocumentationFile>

Inputs for API Docs:
    /Users/david/projects/Sutil/src/Sutil/bin/Debug/netstandard2.0/Sutil.dll
*** /Users/david/projects/Sutil/src/Sutil/bin/Debug/netstandard2.0/Sutil.dll does not exist, has it been built? You may need to provide --properties Configuration=Release.

Substitutions/parameters:
  root --> https://github.com/davedawkins/Sutil/
  fsdocs-authors --> David Dawkins
  fsdocs-collection-name --> Sutil
  fsdocs-collection-name-link --> https://github.com/davedawkins/Sutil/
  fsdocs-logo-src --> https://github.com/davedawkins/Sutil/img/logo.png
  fsdocs-navbar-position --> fixed-left
  fsdocs-theme --> default
  fsdocs-logo-link --> https://github.com/davedawkins/Sutil/
  fsdocs-license-link --> https://github.com/davedawkins/Sutil/blob/master/LICENSE.md
  fsdocs-release-notes-link --> https://github.com/davedawkins/Sutil/blob/master/RELEASE_NOTES.md
  fsdocs-package-project-url --> https://github.com/davedawkins/Sutil/
  fsdocs-package-tags --> fsharp;fable
  fsdocs-package-version --> 1.0.0-alpha-006
  fsdocs-repository-link --> https://github.com/davedawkins/Sutil/
using extra content from /Users/david/.nuget/packages/fsharp.formatting.commandtool/11.4.1/extras
note, no template files: 'docs/reference/_template.html', 'docs/_template.html', 'docs/reference/_template.md', 'docs/_template.md' found, using default template /Users/david/.nuget/packages/fsharp.formatting.commandtool/11.4.1/templates/_template.html

API docs:
  generating model for 1 assemblies in API docs...
  loading 1 assemblies...
isNetCoreApp = true
**** Skipping assembly '/Users/david/projects/Sutil/src/Sutil/bin/Debug/netstandard2.0/Sutil.dll' because was not found in resolved assembly list
  collecting namespaces...
  found 0 namespaces...

Content:
Error : 
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/david/projects/Sutil/docs'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at <StartupCode$fsdocs>.$BuildCommand.clo@171-20.GenerateNext(IEnumerable`1& next) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.CommandTool/BuildCommand.fs:line 190
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 368
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System.Collections.IEnumerator.MoveNext() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 400
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$fsdocs>.$BuildCommand.Convert@213.GenerateNext(IEnumerable`1& next) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.CommandTool/BuildCommand.fs:line 213
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 368
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System.Collections.IEnumerator.MoveNext() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 400
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 546
   at <StartupCode$fsdocs>.$BuildCommand.runDocContentPhase1@702-1.Invoke(Unit unitVar0) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.CommandTool/BuildCommand.fs:line 714
   at <StartupCode$fsdocs>.$BuildCommand.protect@388(CoreBuildOptions this, String phase, FSharpFunc`2 f) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.CommandTool/BuildCommand.fs:line 390
```

**Comment by dsyme** [comment]
Thanks, yes, please contribute a PR to docs and/or better error message

**Comment by dsyme** [comment]
Note this in the log
```
  skipping project 'App.fsproj' because it doesn't have <GenerateDocumentationFile>
  skipping project 'DevTools.fsproj' because it doesn't have <GenerateDocumentationFile>
```

**Comment by dsyme** [comment]
Added https://github.com/fsprojects/FSharp.Formatting/commit/2c93118a9e3d2491803988ab32d752b1210c6f31
